[workspace]
resolver = "2"
members = ["crates/escapement-core"]

[workspace.package]
edition = "2021"
license = "UNLICENSED"
repository = "https://github.com/unsigned-gg/escapement"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
